# Try to find libReadoutCard
# once found this module will define:
#  LIBINFOLOGGER_LIBRARIES
#  LIBINFOLOGGER_INCLUDE_DIRS

find_path(LIBINFOLOGGER_INCLUDE_DIR NAMES "InfoLogger/InfoLogger.hxx"
          PATHS ENV INFOLOGGER_ROOT PATH_SUFFIXES "include")
find_library(LIBINFOLOGGER_LIBRARY NAMES "InfoLogger"
             PATHS ENV INFOLOGGER_ROOT PATH_SUFFIXES "lib")

# message(STATUS "$ENV{INFOLOGGER_ROOT} -> ${LIBINFOLOGGER_INCLUDE_DIR}")
# message(STATUS "$ENV{INFOLOGGER_ROOT} -> ${LIBINFOLOGGER_LIBRARY}")

set(LIBINFOLOGGER_LIBRARIES ${LIBINFOLOGGER_LIBRARY}
    CACHE STRING "Location of DAQ-provided info logger library" FORCE)
set(LIBINFOLOGGER_INCLUDE_DIRS ${LIBINFOLOGGER_INCLUDE_DIR}
    CACHE STRING "Location of DAQ-provided info logger library headers" FORCE)

mark_as_advanced(FORCE LIBINFOLOGGER_INCLUDE_DIR LIBINFOLOGGER_LIBRARY)
